//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostaDiamante_HOA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CostaDiamante_HOA.GlobalMessages", typeof(GlobalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred, plase try again. If error persists, plase send this to the system administrator: .
        /// </summary>
        public static string ERROR_OCURRED {
            get {
                return ResourceManager.GetString("ERROR_OCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel this payment?.
        /// </summary>
        public static string PAY_CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("PAY_CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successfully canceled..
        /// </summary>
        public static string PAY_CANCELED {
            get {
                return ResourceManager.GetString("PAY_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New payment registered..
        /// </summary>
        public static string PAY_NEW {
            get {
                return ResourceManager.GetString("PAY_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment was not found..
        /// </summary>
        public static string PAY_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOA Fees Payments.
        /// </summary>
        public static string PAYMENT_TYPE_HOA_FEE {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE_HOA_FEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Impact Payments.
        /// </summary>
        public static string PAYMENT_TYPE_RENT_IMPACT {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE_RENT_IMPACT", resourceCulture);
            }
        }
    }
}
