//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostaDiamante_HOA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CostaDiamante_HOA.GlobalMessages", typeof(GlobalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails are disabled in system configuration.
        /// </summary>
        public static string ERROR_MSG_EMAILS_DISABLED {
            get {
                return ResourceManager.GetString("ERROR_MSG_EMAILS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No receipients were registered to send the email.
        /// </summary>
        public static string ERROR_MSG_NO_RECEIPIENTS {
            get {
                return ResourceManager.GetString("ERROR_MSG_NO_RECEIPIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred, plase try again. If error persists, plase send this to the system administrator: .
        /// </summary>
        public static string ERROR_OCURRED {
            get {
                return ResourceManager.GetString("ERROR_OCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quarter was &lt;Strong&gt;paid completely&lt;/Strong&gt;..
        /// </summary>
        public static string HOAFEE_COMPLETE_PAID {
            get {
                return ResourceManager.GetString("HOAFEE_COMPLETE_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested address its not recognized by the system, check if its correct..
        /// </summary>
        public static string HTTP_ERROR_BADREQUEST {
            get {
                return ResourceManager.GetString("HTTP_ERROR_BADREQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to request this resource. This is because your user doesn&apos;t have enough permissions.
        ///If you think you have to get access to this information, contact your administrator..
        /// </summary>
        public static string HTTP_ERROR_FORBIDDEN {
            get {
                return ResourceManager.GetString("HTTP_ERROR_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found in the database. Use functions that the system give to list the item you are looking for, if it exists but you are not able to request it, report the error to the administrator..
        /// </summary>
        public static string HTTP_ERROR_NOTFOUND {
            get {
                return ResourceManager.GetString("HTTP_ERROR_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;No visits&lt;/strong&gt; have been registered this year.
        /// </summary>
        public static string NO_VISITS {
            get {
                return ResourceManager.GetString("NO_VISITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No visits have been notified in selected period..
        /// </summary>
        public static string NO_VISITS_FOUND {
            get {
                return ResourceManager.GetString("NO_VISITS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;strong&gt;owner was not registered&lt;/strong&gt; int this whole year..
        /// </summary>
        public static string OWNER_OUTOFYEAR {
            get {
                return ResourceManager.GetString("OWNER_OUTOFYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel this payment?.
        /// </summary>
        public static string PAY_CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("PAY_CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successfully canceled..
        /// </summary>
        public static string PAY_CANCELED {
            get {
                return ResourceManager.GetString("PAY_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New payment registered..
        /// </summary>
        public static string PAY_NEW {
            get {
                return ResourceManager.GetString("PAY_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment was not found..
        /// </summary>
        public static string PAY_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments for Family and/or Friends Rent.
        /// </summary>
        public static string PAYMENT_TYPE_FAMILY_FRIENDS_RENT {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE_FAMILY_FRIENDS_RENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOA Fees Payments.
        /// </summary>
        public static string PAYMENT_TYPE_HOA_FEE {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE_HOA_FEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Impact Payments.
        /// </summary>
        public static string PAYMENT_TYPE_RENT_IMPACT {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE_RENT_IMPACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rents By Year Report.
        /// </summary>
        public static string RENTS_BY_YEAR_REPORT {
            get {
                return ResourceManager.GetString("RENTS_BY_YEAR_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This visit was &lt;Strong&gt;paid completely&lt;/Strong&gt;..
        /// </summary>
        public static string VISIT_COMPLETE_PAID {
            get {
                return ResourceManager.GetString("VISIT_COMPLETE_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit History.
        /// </summary>
        public static string VISIT_HISTORY {
            get {
                return ResourceManager.GetString("VISIT_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter search for arrivals in the selected range of time..
        /// </summary>
        public static string VISIT_HISTORY_LEGEND1 {
            get {
                return ResourceManager.GetString("VISIT_HISTORY_LEGEND1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New visitor added..
        /// </summary>
        public static string VISITOR_NEW {
            get {
                return ResourceManager.GetString("VISITOR_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected visitor was removed..
        /// </summary>
        public static string VISITOR_REMOVED {
            get {
                return ResourceManager.GetString("VISITOR_REMOVED", resourceCulture);
            }
        }
    }
}
