// <auto-generated />
namespace CostaDiamante_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class owner_registrationDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(owner_registrationDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201711261824504_owner_registrationDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
