// <auto-generated />
namespace CostaDiamante_HOA
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class visit_modifiedaddtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(visit_modifiedaddtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201711210236318_visit_modified-add-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
