// <auto-generated />
namespace CostaDiamante_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class numberOfVisitors_Visit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(numberOfVisitors_Visit));
        
        string IMigrationMetadata.Id
        {
            get { return "201802271847508_numberOfVisitors_Visit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
