// <auto-generated />
namespace CostaDiamante_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedFields_UserToOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedFields_UserToOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "201802172302466_changedFields_UserToOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
