// <auto-generated />
namespace CostaDiamante_HOA
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class payments_hoafee_owner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(payments_hoafee_owner));
        
        string IMigrationMetadata.Id
        {
            get { return "201711250306374_payments_hoafee_owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
