// <auto-generated />
namespace CostaDiamante_HOA
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class payments_impactrect_visit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(payments_impactrect_visit));
        
        string IMigrationMetadata.Id
        {
            get { return "201711250606002_payments_impactrect_visit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
