// <auto-generated />
namespace Sonora_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_entity_checkinList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_entity_checkinList));
        
        string IMigrationMetadata.Id
        {
            get { return "201705052152263_added_entity_checkinList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
