// <auto-generated />
namespace Sonora_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationShip_Owner_CheckInList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationShip_Owner_CheckInList));
        
        string IMigrationMetadata.Id
        {
            get { return "201705060157346_relationShip_Owner_CheckInList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
