// <auto-generated />
namespace Sonora_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationship_Changed_permission_condo_visits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationship_Changed_permission_condo_visits));
        
        string IMigrationMetadata.Id
        {
            get { return "201705050455497_relationship_Changed_permission_condo_visits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
