// <auto-generated />
namespace Sonora_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class corrected_ownerIDType_Visits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(corrected_ownerIDType_Visits));
        
        string IMigrationMetadata.Id
        {
            get { return "201705072157243_corrected_ownerIDType_Visits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
