// <auto-generated />
namespace Sonora_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class permissionVisit_Permission_CanBeNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(permissionVisit_Permission_CanBeNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201705130216108_permissionVisit_Permission_CanBeNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
