// <auto-generated />
namespace Sonora_HOA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class condo_ID_to_ownerID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(condo_ID_to_ownerID));
        
        string IMigrationMetadata.Id
        {
            get { return "201705012050261_condo_ID_to_ownerID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
